bwi_scavenger:
  scav_hunt_login:
    email: stefandebruyn@utexas.edu
    password: sick robots
  ws_path: /home/bwilab/scavenger_hunt
  world: sim
  topics:
    perception:
      color: /camera/rgb/image_color
      depth: /camera/depth/image
