scavenger_hunt:
  login:
    email: email@email.comm
    password: PASSWORD_TO_SITE
  website:
          domain: https://scavenger-hunt.cs.utexas.edu/
  topics:
    login: /scavenger_hunt/login
  services:
    get_hunt: /scavenger_hunt/get_hunt
    send_proof: /scavenger_hunt/send_proof
    get_proof_status: /scavenger_hunt/get_proof_status
  scratch_path: ~
